#!/usr/bin/env node

const bandcamp = require('../streams/bandcamp');


const BANDCAMP_URL = "https://americanfood.bandcamp.com/album/wanna-be-a-cat"
console.log("BANDCAMP_URL: " + BANDCAMP_URL);

bandcamp.parseSourcePage(BANDCAMP_URL).then((result) => {
    console.log("URLS: " + result.streams.length);
    console.log(result.streams[0]);
})

