#!/usr/bin/env node

const config = require('../config');
const client = require('../bot/client');
const service = require('../bot/service');


// Welcome to our mix tape
const urls = [];

// Faraquet - Carefully Planned
urls.push("https://www.youtube.com/watch?v=s4A17XOjqto");

// Moin - Crappy Dreams Count 
urls.push("https://m-o-i-n.bandcamp.com/track/crappy-dreams-count");

// Moin - Right Is Alright, Wrong Is To Belong
urls.push("https://m-o-i-n.bandcamp.com/track/right-is-alright-wrong-is-to-belong");

// Cornelius - Drop
urls.push("https://corneliusofficial.bandcamp.com/track/drop");

// Cornelius - Point Of View Point
urls.push("https://corneliusofficial.bandcamp.com/track/point-of-view-point");

// Dry Cleaning - Magic of Meghan
urls.push("https://drycleaning.bandcamp.com/track/magic-of-meghan");

// Jeff Parker - Suffolk
urls.push("https://intlanthem.bandcamp.com/track/suffolk");

// Terry Allen and the Panhandle Mystery Band  - Pirate Jenny
urls.push("https://terryallen.bandcamp.com/track/pirate-jenny");

// Larnell Lewis - The City Lights
urls.push("https://larnelllewis.bandcamp.com/track/the-city-lights");

// Middle Class Rut - Lifelong Dayshift
urls.push("https://brightantennarecords.bandcamp.com/track/lifelong-dayshift");

// Smart Went Crazy - DC Will Do That To You
urls.push("https://smartwentcrazy.bandcamp.com/track/dc-will-do-that-to-you");

// Spidergawd - Tourniquet
urls.push("https://soundcloud.com/spidergawd/tourniquet");

// Lifetime - Ferret
urls.push("https://lifetimenj.bandcamp.com/track/ferret");

// Kid Dynamite - Heart A Tact
urls.push("https://kiddynamitephl.bandcamp.com/track/heart-a-tact-2");

// With Honor Rethink, Return
urls.push("https://purenoise.bandcamp.com/track/rethink-return-2021-remastered");

// Shipyards - Headfirst Dive
urls.push("https://soundcloud.com/shipyards/headfirst-dive");

// Sea Graves - Don't Try
urls.push("https://seagravesbk.bandcamp.com/track/dont-try");


const player = service.makePlayer(config);
const pawn = client.makeClient(config, player);

player.setPlaylist(urls);

pawn.login(config.botToken);
